version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: username
      POSTGRES_PASSWORD: the_secret_password

  web:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DEBUG: 'True'
      SECRET_KEY: "django-insecure-sc_@xqrd-^47zx#u-e=e_o7b62c+tzes2-j*c=l82mc*z*wh8x"
      POSTGRES_DB: db_name
      POSTGRES_USER: username
      POSTGRES_PASSWORD: the_secret_password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  pgdata:
